USE [master]
GO

/****** Object:  Database [BooksExampleDB]    Script Date: 15/07/2022 06:25:11 ******/
CREATE DATABASE [BooksExampleDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BooksExampleDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BooksExampleDB_Primary.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BooksExampleDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BooksExampleDB_Primary.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BooksExampleDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BooksExampleDB] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [BooksExampleDB] SET ANSI_NULLS ON 
GO

ALTER DATABASE [BooksExampleDB] SET ANSI_PADDING ON 
GO

ALTER DATABASE [BooksExampleDB] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [BooksExampleDB] SET ARITHABORT ON 
GO

ALTER DATABASE [BooksExampleDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BooksExampleDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BooksExampleDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BooksExampleDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BooksExampleDB] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [BooksExampleDB] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [BooksExampleDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BooksExampleDB] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [BooksExampleDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BooksExampleDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BooksExampleDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BooksExampleDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BooksExampleDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BooksExampleDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BooksExampleDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BooksExampleDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BooksExampleDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BooksExampleDB] SET RECOVERY FULL 
GO

ALTER DATABASE [BooksExampleDB] SET  MULTI_USER 
GO

ALTER DATABASE [BooksExampleDB] SET PAGE_VERIFY NONE  
GO

ALTER DATABASE [BooksExampleDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BooksExampleDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BooksExampleDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BooksExampleDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BooksExampleDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BooksExampleDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BooksExampleDB] SET  READ_WRITE 
GO


