
INSERT INTO Author ( Name ) VALUES ('William Shakespeare');
INSERT INTO Author ( Name ) VALUES ('Christian Church');
INSERT INTO Author ( Name ) VALUES ('Miguel de Cervantes');
INSERT INTO Author ( Name ) VALUES ('Homer');
INSERT INTO Author ( Name ) VALUES ('Homer');
INSERT INTO Author ( Name ) VALUES ('Ovid');
INSERT INTO Author ( Name ) VALUES ('James Joyce');
INSERT INTO Author ( Name ) VALUES ('Aeschylus');
INSERT INTO Author ( Name ) VALUES ('Lao Tsu');
INSERT INTO Author ( Name ) VALUES ('Fyodor Dostoyevsky');
INSERT INTO Author ( Name ) VALUES ('Lewis Carroll');
INSERT INTO Author ( Name ) VALUES ('Virginia Woolf');
INSERT INTO Author ( Name ) VALUES ('Gabriel Garcia Marquez');
INSERT INTO Author ( Name ) VALUES ('Vladimir Nabokov');
INSERT INTO Author ( Name ) VALUES ('Dante Alighieri');
INSERT INTO Author ( Name ) VALUES ('Wallace Stevens');
INSERT INTO Author ( Name ) VALUES ('India Iran Iraq Egypt');
INSERT INTO Author ( Name ) VALUES ('Leo Tolstoy');
INSERT INTO Author ( Name ) VALUES ('Toni Morrison');
INSERT INTO Author ( Name ) VALUES ('Jorge Luis Borges');
INSERT INTO Author ( Name ) VALUES ('Joseph Conrad');
INSERT INTO Author ( Name ) VALUES ('Isak Dinesen');
INSERT INTO Author ( Name ) VALUES ('Sophocles');
INSERT INTO Author ( Name ) VALUES ('Sophocles');
INSERT INTO Author ( Name ) VALUES ('Sophocles');
INSERT INTO Author ( Name ) VALUES ('Roberto Calasso');
INSERT INTO Author ( Name ) VALUES ('Somadeva');
INSERT INTO Author ( Name ) VALUES ('Anton Chekhov');
INSERT INTO Author ( Name ) VALUES ('Vyasa');
INSERT INTO Author ( Name ) VALUES ('James Joyce');
INSERT INTO Author ( Name ) VALUES ('Brothers Grimm');
INSERT INTO Author ( Name ) VALUES ('Ralph Ellison');
INSERT INTO Author ( Name ) VALUES ('William Faulkner');
INSERT INTO Author ( Name ) VALUES ('D. H. Lawrence');
INSERT INTO Author ( Name ) VALUES ('Vladimir Nabokov');
INSERT INTO Author ( Name ) VALUES ('Plato');
INSERT INTO Author ( Name ) VALUES ('Marcel Proust');
INSERT INTO Author ( Name ) VALUES ('Günter Grass');
INSERT INTO Author ( Name ) VALUES ('Flannery O Connor');
INSERT INTO Author ( Name ) VALUES ('Charles Dickens');
INSERT INTO Author ( Name ) VALUES ('Samuel Beckett');
INSERT INTO Author ( Name ) VALUES ('Samuel Beckett');
INSERT INTO Author ( Name ) VALUES ('Samuel Beckett');
INSERT INTO Author ( Name ) VALUES ('Sigmund Freud');
INSERT INTO Author ( Name ) VALUES ('Geoffrey Chaucer');
INSERT INTO Author ( Name ) VALUES ('T. S. Eliot');
INSERT INTO Author ( Name ) VALUES ('Gustave Flaubert');
INSERT INTO Author ( Name ) VALUES ('Salman Rushdie');
INSERT INTO Author ( Name ) VALUES ('Laurence Sterne');
INSERT INTO Author ( Name ) VALUES ('W. B. Yeats');
INSERT INTO Author ( Name ) VALUES ('James George Frazer');
INSERT INTO Author ( Name ) VALUES ('Kenneth Grahame');
INSERT INTO Author ( Name ) VALUES ('Jane Austen');
INSERT INTO Author ( Name ) VALUES ('Iris Murdoch');
INSERT INTO Author ( Name ) VALUES ('Jan Potocki');
INSERT INTO Author ( Name ) VALUES ('Euripides');
INSERT INTO Author ( Name ) VALUES ('William Makepeace Thackeray');
INSERT INTO Author ( Name ) VALUES ('Franz Kafka');
INSERT INTO Author ( Name ) VALUES ('Virgil');
INSERT INTO Author ( Name ) VALUES ('Gottfried von Strassburg');
INSERT INTO Author ( Name ) VALUES ('William Blake');
INSERT INTO Author ( Name ) VALUES ('Apuleius');
INSERT INTO Author ( Name ) VALUES ('Samuel Beckett');
INSERT INTO Author ( Name ) VALUES ('Samuel Beckett');
INSERT INTO Author ( Name ) VALUES ('Emily Dickinson');
INSERT INTO Author ( Name ) VALUES ('Herman Melville');
INSERT INTO Author ( Name ) VALUES ('Vladimir Nabokov');
INSERT INTO Author ( Name ) VALUES ('Jean Racine');
INSERT INTO Author ( Name ) VALUES ('Aristotle');
INSERT INTO Author ( Name ) VALUES ('Ivan Turgenev');
INSERT INTO Author ( Name ) VALUES ('Aristophanes');
INSERT INTO Author ( Name ) VALUES ('Henrik Ibsen');
INSERT INTO Author ( Name ) VALUES ('Oscar Wilde');
INSERT INTO Author ( Name ) VALUES ('Ernest Hemingway');
INSERT INTO Author ( Name ) VALUES ('E. B. White');
INSERT INTO Author ( Name ) VALUES ('Mark Twain');
INSERT INTO Author ( Name ) VALUES ('Walt Whitman');
INSERT INTO Author ( Name ) VALUES ('Italo Calvino');
INSERT INTO Author ( Name ) VALUES ('Charlotte Bronte');
INSERT INTO Author ( Name ) VALUES ('Mario Vargas Llosa');
INSERT INTO Author ( Name ) VALUES ('Heraclitus');
INSERT INTO Author ( Name ) VALUES ('Emily Bront');
INSERT INTO Author ( Name ) VALUES ('Unknown');
INSERT INTO Author ( Name ) VALUES ('Fyodor Dostoyevsky');
INSERT INTO Author ( Name ) VALUES ('Thomas Hardy');
INSERT INTO Author ( Name ) VALUES ('Murasaki Shikibu');
INSERT INTO Author ( Name ) VALUES ('Michel de Montaigne');
INSERT INTO Author ( Name ) VALUES ('Henry David Thoreau');
INSERT INTO Author ( Name ) VALUES ('Richard Wright');
INSERT INTO Author ( Name ) VALUES ('Ralph Waldo Emerson');
INSERT INTO Author ( Name ) VALUES ('Thomas Mann');
INSERT INTO Author ( Name ) VALUES ('Harper Lee');
INSERT INTO Author ( Name ) VALUES ('Francois Rabelais');
INSERT INTO Author ( Name ) VALUES ('John Milton');
INSERT INTO Author ( Name ) VALUES ('Henry Fielding');
INSERT INTO Author ( Name ) VALUES ('J. D. Salinger');
INSERT INTO Author ( Name ) VALUES ('Frances A. Yates');
INSERT INTO Author ( Name ) VALUES ('George Eliot');
INSERT INTO Author ( Name ) VALUES ('Peter Matthiessen');
INSERT INTO Author ( Name ) VALUES ('Cormac McCarthy');
INSERT INTO Author ( Name ) VALUES ('Voltaire');
INSERT INTO Author ( Name ) VALUES ('Friedrich Nietzsche');
INSERT INTO Author ( Name ) VALUES ('E. M. Forster');
INSERT INTO Author ( Name ) VALUES ('Iris Murdoch');
INSERT INTO Author ( Name ) VALUES ('Claude Lévi-Strauss');
INSERT INTO Author ( Name ) VALUES ('Zora Neale Hurston');



INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'First Folio', 'Mr. William Shakespeares Comedies, Histories, & Tragedies is the 1623 published collection of William Shakespeare|Chr(39)| s plays. Modern scholars commonly refer to it as the First Folio. Printed in folio...', 'https://d3i5mgdwi2ze58.cloudfront.net/7dgcifd3wgbjbjkmhiqlp77v7hwv');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'The Bible', 'The Authorized King James Version is an English translation of the Christian Bible begun in 1604 and completed in 1611 by the Church of England. Printed by the King|Chr(39)|s Printer, Robert Barker, the fi...', 'https://d3i5mgdwi2ze58.cloudfront.net/e90tvfwlm6iq1vhsspsx9tzdxna7');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Don Quixote', 'Alonso Quixano, a retired country gentleman in his fifties, lives in an unnamed section of La Mancha with his niece and a housekeeper. He has become obsessed with books of chivalry, and believes th...', 'https://d3i5mgdwi2ze58.cloudfront.net/bn8dmzg3y0fcofvl6azmbyl6bry4');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'The Iliad', 'The Iliad is an epic poem in dactylic hexameters, traditionally attributed to Homer. Set in the Trojan War, the ten-year siege of Ilium by a coalition of Greek states, it tells of the battles and e...', 'https://d3i5mgdwi2ze58.cloudfront.net/kudnd6hjgwhd190ozepfx6g8js7g');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'The Odyssey', 'The Odyssey is one of two major ancient Greek epic poems attributed to Homer. It is, in part, a sequel to the Iliad, the other work traditionally ascribed to Homer. The poem is fundamental to the m...', 'https://d3i5mgdwi2ze58.cloudfront.net/jyx2n4emuiwjjfu682ylkh10xyoj');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Metamorphoses', 'The Metamorphoses by the Roman poet Ovid is a narrative poem in fifteen books that describes the creation and history of the world. Completed in 8 AD, it has remained one of the most popular works ...', 'https://d3i5mgdwi2ze58.cloudfront.net/mqityjzj68pnkan4g72cvd892fgj');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Finnegans Wake', 'Having done the longest day in literature with his monumental Ulysses (1922), James Joyce set himself an even greater challenge for his next book — the night. "A nocturnal state.... That is what I ...', 'https://d3i5mgdwi2ze58.cloudfront.net/1jtstxewqjt615belujwkymctoh7');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Oresteia', 'The Oresteia is a trilogy of Greek tragedies written by Aeschylus which concerns the end of the curse on the House of Atreus. When originally performed it was accompanied by Proteus, a satyr play t...', 'https://d3i5mgdwi2ze58.cloudfront.net/v203u43a8m0r79n0eh3qxzzn456c');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Tao Te Ching', 'The Tao Te Ching or Dao De Jing, originally known as Laozi, a record-keeper at the Zhou Dynasty court, by whose name the text is known in China. The text|Chr(39)| true authorship and date of composition o...', 'https://d3i5mgdwi2ze58.cloudfront.net/d9a7pxszaupsrvi8hb01dmfgzfbm');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'The Brothers Karamazov', 'Dostoevsky|Chr(39)| last and greatest novel, The Karamazov Brothers, is both a brilliantly told crime story and a passionate philosophical debate. The dissolute landowner Fyodor Pavlovich Karamazov is mur...', 'https://d3i5mgdwi2ze58.cloudfront.net/ctt318djdthx536i3glgdw270dyq');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Alice|Chr(39)| Adventures in Wonderland', 'In 1862 Charles Lutwidge Dodgson, a shy Oxford mathematician with a stammer, created a story about a little girl tumbling down a rabbit hole. Thus began the immortal adventures of Alice, perhaps th...', 'https://d3i5mgdwi2ze58.cloudfront.net/f8uct7xgd8cz5cw1dsz54zc6swlc');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'To the Lighthouse', 'A landmark novel of high modernism, the text, centering on the Ramsay family and their visits to the Isle of Skye in Scotland between 1910 and 1920, skillfully manipulates temporality and psycholog...', 'https://d3i5mgdwi2ze58.cloudfront.net/txbtrh9toknoba6u0ap8j8jum7qt');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'One Hundred Years of Solitude', 'One of the 20th century|Chr(39)| enduring works, One Hundred Years of Solitude is a widely beloved and acclaimed novel known throughout the world, and the ultimate achievement in a Nobel Prize–winning car...', 'https://d3i5mgdwi2ze58.cloudfront.net/j7koelfcv0va5zky4x1ccmpsgcsb');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Pale Fire', 'The novel is presented as a poem titled "Pale Fire" with commentary by a friend of the poet|Chr(39)|. Together these elements form two story lines in which both authors are central characters. The int...', 'https://d3i5mgdwi2ze58.cloudfront.net/puqf2c4yqf3nw2bf2yel0w0vtmrx');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'The Divine Comedy', 'Belonging in the immortal company of the great works of literature, Dante Alighieri|Chr(39)| poetic masterpiece, The Divine Comedy, is a moving human drama, an unforgettable visionary journey through the ...', 'https://d3i5mgdwi2ze58.cloudfront.net/r3pnyg732gdvkmh8pik9p0b5ct6y');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Collected Poems', 'Wallace Stevens (October 2, 1879 – August 2, 1955) was an American Modernist poet. He was born in Reading, Pennsylvania, educated at Harvard and then New York Law School, and he spent most of his l...', 'https://d3i5mgdwi2ze58.cloudfront.net/22t7m75kv9m5jkgx79yji1p5g9zb');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'One Thousand and One Nights', 'One Thousand and One Nights is a collection of Middle Eastern and South Asian stories and folk tales compiled in Arabic during the Islamic Golden Age. It is often known in English as the Arabian Ni...', 'https://d3i5mgdwi2ze58.cloudfront.net/consucm8tbyk49godu2uf0yngy3c');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'War and Peace', 'Epic in scale, War and Peace delineates in graphic detail events leading up to Napoleon|Chr(39)| invasion of Russia, and the impact of the Napoleonic era on Tsarist society, as seen through the eyes of fi...', 'https://d3i5mgdwi2ze58.cloudfront.net/hwi2qqngyicqz7s7ps4x4k1ei14k');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Beloved', 'Beloved (1987) is a Pulitzer Prize-winning novel by Nobel laureate Toni Morrison. The novel, her fifth, is loosely based on the life and legal case of the slave Margaret Garner, about whom Morrison...', 'https://d3i5mgdwi2ze58.cloudfront.net/rgbp8t53jgjxf52ibulydun84k0m');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Collected Fiction', 'From his 1935 debut with The Universal History of Iniquity, through his immensely influential collections Ficciones and The Aleph, these enigmatic, elaborate, imaginative inventions display Borges...', 'https://d3i5mgdwi2ze58.cloudfront.net/zjdebfocqm8e1ynism67t1434h8m');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Heart of Darkness', 'The story details an incident when Marlow, an Englishman, took a foreign assignment from a Belgian trading company as a ferry-boat captain in Africa. Although Conrad does not specify the name of th...', 'https://d3i5mgdwi2ze58.cloudfront.net/tyxilwq93riaj4702yj9ntkf6o8g');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Anecdotes of Destiny', 'These five rich, witty and magical stories from the author of Out of Africa include one of her most well known tales, ‘Babette’s Feast’, which was made into the classic film. It tells the story of ...', 'https://d3i5mgdwi2ze58.cloudfront.net/02qnf9f7dgi8suvlpte4ffl42ywe');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Oedipus the King', 'Oedipus the King is an Athenian tragedy by Sophocles that was first performed c. 429 BC. It was the second of Sophocles|Chr(39)| three Theban plays to be produced, but it comes first in the internal chron...', 'https://d3i5mgdwi2ze58.cloudfront.net/rcn91ow9bsq20n18to86o3lq048s');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Oedipus at Colonus', 'Oedipus at Colonus is one of the three Theban plays of the Athenian tragedian Sophocles. It was written shortly before Sophocles death in 406 BC and produced by his grandson (also called Sophocles...', 'https://d3i5mgdwi2ze58.cloudfront.net/hm4db29jtbko180djeqyzi3zvgac');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Antigone', 'Antigone is a tragedy by Sophocles written before or in 442 BC. Chronologically, it is the third of the three Theban plays but was written first.[1] The play expands on the Theban legend that preda...', 'https://d3i5mgdwi2ze58.cloudfront.net/elxqx19ti2sn9vccsk2h64h7iqhc');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'The Marriage Of Cadmus And Harmony', 'THE MARRIAGE OF CADMUS AND HARMONY is a book without any modern parallel. Forming an active link in a chain that reaches back through Ovid|Chr(39)| METAMORPHOSES directly to Homer, Roberto Calasso|Chr(39)| re-ex...', 'https://d3i5mgdwi2ze58.cloudfront.net/lhpsd00u1d78aqu9diwjrkui3le4');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Tales from the Kathasaritsagara', 'The vast ocean of stories that influenced storytelling the world over "The Kathasaritasagara" is said to have been compiled by a Kashmiri Saivite Brahmin called Somadeva in AD 1070, although the da...', 'https://d3i5mgdwi2ze58.cloudfront.net/q7c5kf18wf6ey9go51qzdeg0non4');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'The Stories of Anton Chekhov', 'Anton Pavlovich Chekhov was a Russian short-story writer, playwright and physician, considered to be one of the greatest short-story writers in the history of world literature. His career as a dram...', 'https://d3i5mgdwi2ze58.cloudfront.net/iif8mxlx7cok3bj24pkmac1spy6d');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Mahabharata', 'The Mahabharata is one of the two major Sanskrit epics of ancient India, the other being the Rāmāyaṇa. The epic is part of the Hindu itihāsa (literally "history"), and forms an important part of Hi...', 'https://d3i5mgdwi2ze58.cloudfront.net/7sxlmcc88ta9ab9p7fipw6bna70z');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Ulysses', 'Ulysses chronicles the passage of Leopold Bloom through Dublin during an ordinary day, June 16, 1904. The title parallels and alludes to Odysseus (Latinised into Ulysses), the hero of Homer|Chr(39)| Odyss...', 'https://d3i5mgdwi2ze58.cloudfront.net/f7nkbyqfsnrrlct3hs01jkrz2vdi');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Household Tales', 'Children|Chr(39)| and Household Tales (German: Kinder- und Hausmärchen) is a collection of German origin fairy tales first published in 1812 by Jacob and Wilhelm Grimm, the Brothers Grimm. The collection ...', 'https://d3i5mgdwi2ze58.cloudfront.net/lpv7jeht3xve0hhm6t21udglbp8i');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Invisible Man ', 'The novel addresses many of the social and intellectual issues facing African-Americans in the early twentieth century, including black nationalism, the relationship between black identity and Marx...', 'https://d3i5mgdwi2ze58.cloudfront.net/r9z7olkoavrv49e8emd943ui5qvr');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Absalom, Absalom!', 'Absalom, Absalom! is a Southern Gothic novel by the American author William Faulkner, first published in 1936. It is a story about three families of the American South, taking place before, during,...', 'https://d3i5mgdwi2ze58.cloudfront.net/sm15lqtnyzz03dctpcpjt3jnpqo4');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Women in Love', 'Perhaps no other of the world’s great writers lived and wrote with the passionate intensity of D. H. Lawrence. And perhaps no other of his books so explores the mysteries between men and women–both...', 'https://d3i5mgdwi2ze58.cloudfront.net/k32ynw0jpj98ralg7m8vjh4r6ey5');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Lolita ', 'The book is internationally famous for its innovative style and infamous for its controversial subject: the protagonist and unreliable narrator, middle aged Humbert Humbert, becomes obsessed and se...', 'https://d3i5mgdwi2ze58.cloudfront.net/cuqzoi0t52xnb7cjhdzrfuc7rjj4');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'The Complete Works of Plato', 'Plato (pronounced /ˈpleɪtoʊ/) (Greek: Πλάτων, Plátōn, "broad") (428/427 BC[a] – 348/347 BC), was a Classical Greek philosopher, mathematician, writer of philosophical dialogues, and founder of the ...', 'https://d3i5mgdwi2ze58.cloudfront.net/uasqpzo6ibrfv0vebgx9j2t8wfhk');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'In Search of Lost Time ', '|Chr(39)|wann|Chr(39)| Way, the first part of A la recherche de temps perdu, Marcel Proust|Chr(39)| seven-part cycle, was published in 1913. In it, Proust introduces the themes that run through the entire work. The narr...', 'https://d3i5mgdwi2ze58.cloudfront.net/7hqv6ddaqv363p4hadx6lymotow1');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'The Tin Drum', 'Acclaimed as the greatest German novel written since the end of World War II, The Tin Drum is the autobiography of thirty-year-old Oskar Matzerath, who has lived through the long Nazi nightmare and...', 'https://d3i5mgdwi2ze58.cloudfront.net/njovuzqlp4cqje96g4x4b7q1nbdt');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'The Complete Stories of Flannery O Connor', 'The publication of this extraordinary volume firmly established Flannery O Connor|Chr(39)| monumental contribution to American fiction. There are thirty-one stories here in all, including twelve that do n...', 'https://d3i5mgdwi2ze58.cloudfront.net/l5amdh5yy3fj3oaes0aig3kiktgk');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Great Expectations', 'Great Expectations is written in the genre of "bildungsroman" or the style of book that follows the story of a man or woman in their quest for maturity, usually starting from childhood and ending i...', 'https://d3i5mgdwi2ze58.cloudfront.net/p1hex7c8wgkjjvks6pogmjloyj0p');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Molloy', 'Molloy is a novel by Samuel Beckett. The English translation is by Beckett and Patrick Bowles.', 'https://d3i5mgdwi2ze58.cloudfront.net/aqjslfdcsw9e3kdbypnd9j02xbdk');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Malone Dies', 'Malone Dies is a novel by Samuel Beckett. It was first published in 1951, in French, as Malone Meurt, and later translated into English by the author.', 'https://d3i5mgdwi2ze58.cloudfront.net/4i6hz4byptdq81asj95qkhrbpmbg');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'The Unnamable', 'The Unnamable is a 1953 novel by Samuel Beckett. It is the third and final entry in Beckett|Chr(39)| "Trilogy" of novels, which begins with Molloy followed by Malone Dies. It was originally published in F...', 'https://d3i5mgdwi2ze58.cloudfront.net/wjg19pcrzxv0hiqc5kdb2jgdv2ed');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'The Interpretation of Dreams', 'This book introduces Freud|Chr(39)| theory of the unconscious with respect to dream interpretation. Dreams, in Freud|Chr(39)| view, were all forms of "wish-fulfillment" — attempts by the unconscious to resolve a...', 'https://d3i5mgdwi2ze58.cloudfront.net/2733wwbqgjsk4ry49wsgmndjt0b3');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'The Canterbury Tales', 'With their astonishing diversity of tone and subject matter, The Canterbury Tales have become one of the touchstones of medieval literature. Translated here into modern English, these tales of a mo...', 'https://d3i5mgdwi2ze58.cloudfront.net/bcly10g4x8ogq8odkwbltz0afey7');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Four Quartets', 'Four Quartets is a set of four poems written by T. S. Eliot that were published individually over a six-year period. The first poem, Burnt Norton, was written and published with a collection of his...', 'https://d3i5mgdwi2ze58.cloudfront.net/eo68j364onqjuj4n4nv402fl6p70');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Madame Bovary', 'For daring to peer into the heart of an adulteress and enumerate its contents with profound dispassion, the author of Madame Bovary was tried for "offenses against morality and religion." What shoc...', 'https://d3i5mgdwi2ze58.cloudfront.net/rtw3xjyjbcouewfrbpz5lcx5e6yf');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Midnight|Chr(39)| Children ', 'Midnight|Chr(39)| Children is a loose allegory for events in India both before and, primarily, after the independence and partition of India, which took place at midnight on 15 August 1947. The protagonis...', 'https://d3i5mgdwi2ze58.cloudfront.net/k7ca7dt6b2s35w1salpiewwl86cw');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Tristram Shandy', 'As its title suggests, the book is ostensibly Tristram|Chr(39)| narration of his life story. But it is one of the central jokes of the novel that he cannot explain anything simply, that he must make expla...', 'https://d3i5mgdwi2ze58.cloudfront.net/zxuwg9q6du2kazlgngkynslgof5o');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Collected Poems of W. B. Yeats', 'William Butler Yeats was an Irish poet, dramatist, and one of the foremost figures of 20th century literature.', 'https://d3i5mgdwi2ze58.cloudfront.net/0oz0lshni1gaqps0cfjpwem1rwdh');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'The Golden Bough', 'The Golden Bough: A Study in Magic and Religion is a wide-ranging, comparative study of mythology and religion, written by Scottish anthropologist Sir James George Frazer (1854–1941). It first was ...', 'https://d3i5mgdwi2ze58.cloudfront.net/ss69eekgnm0t2g9c29kpc5uoybfs');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'The Wind in the Willows', 'A classic in children|Chr(39)| literature The Wind in the Willow is alternately slow moving and fast paced. The book focuses on four anthropomorphised animal characters in a pastoral version of England. T...', 'https://d3i5mgdwi2ze58.cloudfront.net/nkquf3s0dc5o5x5omg0b0m06pto0');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Pride and Prejudice', 'The book is narrated in free indirect speech following the main character Elizabeth Bennet as she deals with matters of upbringing, marriage, moral rightness and education in her aristocratic socie...', 'https://d3i5mgdwi2ze58.cloudfront.net/k4thdrwtugqhuvacwpowkkuivis8');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'The Black Prince', 'Bradley Pearson, an unsuccessful novelist in his late fifties, has finally left his dull office job as an Inspector of Taxes. Bradley hopes to retire to the country, but predatory friends and relat...', 'https://d3i5mgdwi2ze58.cloudfront.net/nfpowqw90vfe6y2ufslav6r3sgra');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'The Manuscript Found in Saragossa', 'Alphonse, a young Walloon officer, is travelling to join his regiment in Madrid in 1739. But he soon finds himself mysteriously detained at a highway inn in the strange and varied company of thieve...', 'https://d3i5mgdwi2ze58.cloudfront.net/qnr4bur2tk4popwkeogunj98kjvs');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'The Bacchae', 'Electra or Elektra (Ancient Greek: Ἠλέκτρα, Ēlektra) is a Greek tragedy by Sophocles. Its date is not known, but various stylistic similarities with the Philoctetes (409 BC) and the Oedipus at Colo...', 'https://d3i5mgdwi2ze58.cloudfront.net/1098a11yesp3o48axbgizk09ihlw');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Vanity Fair', 'No one is better equipped in the struggle for wealth and worldly success than the alluring and ruthless Becky Sharp, who defies her impoverished background to clamber up the class ladder. Her senti...', 'https://d3i5mgdwi2ze58.cloudfront.net/2oxyvzny5s56olfaurttiuaihcmj');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'The Metamorphosis', 'The Metamorphosis (German: Die Verwandlung) is a novella by Franz Kafka, first published in 1915. It is often cited as one of the seminal works of short fiction of the 20th century and is widely st...', 'https://d3i5mgdwi2ze58.cloudfront.net/hydczot2gndh6kx6an28gxreuvev');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'The Aeneid', 'The Aeneid is a Latin epic poem written by Virgil in the late 1st century BC (29–19 BC) that tells the legendary story of Aeneas, a Trojan who traveled to Italy, where he became the ancestor of the...', 'https://d3i5mgdwi2ze58.cloudfront.net/bdjtnqfkd1uleimz20s75kbx9j9h');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Tristan', 'Gottfried|Chr(39)| work is regarded, alongside Wolfram von Eschenbach|Chr(39)| Parzival and the Nibelungenlied, as one of the great narrative masterpieces of the German Middle Ages.', 'https://d3i5mgdwi2ze58.cloudfront.net/0zmctepa91ftyyu2ae1m5it2gntc');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'The Complete Poetry and Prose of William Blake', 'William Blake (28 November 1757 – 12 August 1827) was an English painter, poet and printmaker. Largely unrecognised during his lifetime, Blake is now considered a seminal figure in the history of t...', 'https://d3i5mgdwi2ze58.cloudfront.net/ioxdsfduin33i7ogv5oy3pb99ccj');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'The Golden Ass (Metamorphoses): Or Metamorphoses', 'Apuleius (c. 125-c. 180) was a student of Platonist philosophy and Latin prose writer who produced the novel "Metamorphoses", more popularly known as "The Golden Ass". This work is the only Latin n...', 'https://d3i5mgdwi2ze58.cloudfront.net/r5xlhjfivs973jh1xvk1j7lf2obp');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Waiting for Godot', 'Waiting for Godot (pronounced /ˈɡɒdoʊ/) is a play by Samuel Beckett, in which two characters, Vladimir and Estragon, wait for someone named Godot. Godot|Chr(39)| absence, as well as numerous other aspects...', 'https://d3i5mgdwi2ze58.cloudfront.net/ionxtlcnriayp5cjx43cstn6mr3f');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Endgame', 'Endgame, by Samuel Beckett, is a one-act play with four characters, written in a style associated with the Theatre of the Absurd. It was originally written in French (entitled Fin de partie); as wa...', 'https://d3i5mgdwi2ze58.cloudfront.net/88dxfcq1rg53ezv2gsrfg4yai3pb');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Poems of Emily Dickinson', 'Emily Elizabeth Dickinson (December 10, 1830 – May 15, 1886) was an American poet. Born in Amherst, Massachusetts, to a successful family with strong community ties, she lived a mostly introverted ...', 'https://d3i5mgdwi2ze58.cloudfront.net/8n77j23p6ipuqjbvkbi05t5fpw83');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Moby Dick', 'First published in 1851, Melville|Chr(39)| masterpiece is, in Elizabeth Hardwick|Chr(39)| words, "the greatest novel in American literature." The saga of Captain Ahab and his monomaniacal pursuit of the white wh...', 'https://d3i5mgdwi2ze58.cloudfront.net/epke1jolmtb858vv9ctbtxpa8yi6');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( '|Chr(39)|peak, Memory', '|Chr(39)|peak, Memory is an autobiographical memoir by writer Vladimir Nabokov. The first twelve chapters describe Nabokov|Chr(39)| remembrance of his youth in a quasi-aristocratic family living in pre-revolut...', 'https://d3i5mgdwi2ze58.cloudfront.net/fzarqwiwmm7n5srqv04j8r3ivddj');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Phèdre', 'Phèdre (originally Phèdre et Hippolyte) is a dramatic tragedy in five acts written in alexandrine verse by Jean Racine, first performed in 1677.', 'https://d3i5mgdwi2ze58.cloudfront.net/b7qtc8kvnx7iqia3d63gs0pvimq1');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Poetics', 'Aristotle|Chr(39)| Poetics (Greek: Περὶ ποιητικῆς, Latin: De Poetica;[1] c. 335 BCE[2]) is the earliest surviving work of dramatic theory and the first extant philosophical treatise to focus on literary t...', 'https://d3i5mgdwi2ze58.cloudfront.net/9mded85vxk6i8dcthtwusgqek3co');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Fathers and Sons', 'Fathers and Sons is an 1862 novel by Ivan Turgenev, his best known work. The fathers and children of the novel refers to the growing divide between the two generations of Russians, and the chara...', 'https://d3i5mgdwi2ze58.cloudfront.net/qzaviwb2cm8r4m22yqn9nh3vfgm2');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Lysistrata', 'This classic comedy — from the 5th century BC — concerns the vow of Greek women to withhold sex from their husbands until the men agree to end the disastrous wars between Athens and Sparta. An exub...', 'https://d3i5mgdwi2ze58.cloudfront.net/z9es5lhppu3uxflaq7y95hu9umue');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'A Doll|Chr(39)| House', 'A Doll|Chr(39)| House is an 1879 play by Norwegian playwright Henrik Ibsen. Written one year after The Pillars of Society, the play was the first of Ibsen|Chr(39)| to create a sensation and is now perhaps his mo...', 'https://d3i5mgdwi2ze58.cloudfront.net/9dzhfs0rtr9ibfyg7a01dmqnplyn');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'The Importance of Being Earnest', 'The Importance of Being Earnest, A Trivial Comedy for Serious People is a play by Oscar Wilde. First performed on 14 February 1895 at the St James|Chr(39)| Theatre in London, it is a farcical comedy in wh...', 'https://d3i5mgdwi2ze58.cloudfront.net/38qxuwrm3ynjz8sna6fgn0vgrwhn');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'A Farewell to Arms', 'The novel is told through the point of view of Lieutenant Frederic Henry, an American serving as an ambulance driver in the Italian army during World War I.', 'https://d3i5mgdwi2ze58.cloudfront.net/xhe9j5s79esy88oggjage2k0k4zd');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Charlotte|Chr(39)| Web', 'The novel tells the story of a pig named Wilbur and his friendship with a barn spider named Charlotte. When Wilbur is in danger of being slaughtered by the farmer, Charlotte writes messages praisin...', 'https://d3i5mgdwi2ze58.cloudfront.net/b8gmmodnizudboxrtrrih182raes');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'The Adventures of Huckleberry Finn', 'Revered by all of the town|Chr(39)| children and dreaded by all of its mothers, Huckleberry Finn is indisputably the most appealing child-hero in American literature. Unlike the tall-tale, idyllic worl...', 'https://d3i5mgdwi2ze58.cloudfront.net/phz3vc780qvnafu8phrzjyptq75a');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Leaves of Grass', 'Leaves of Grass (1855) is a poetry collection by the American poet Walt Whitman. Among the poems in the collection are "Song of Myself," "I Sing the Body Electric," "Out of the Cradle Endlessly Roc...', 'https://d3i5mgdwi2ze58.cloudfront.net/sipfu1oc66rend55gj85ymtfb9e8');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'If on a Winter|Chr(39)| Night a Traveller ', 'Calvino|Chr(39)| anti-novel is about the efforts of his two characters — a man called only The Reader, and the Other Reader, a woman named Ludmilla — to read ten very different novels. They are never able...', 'https://d3i5mgdwi2ze58.cloudfront.net/nltr723521t6id0s9oiunx7h61eb');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Jane Eyre', 'Jane Eyre is a first-person narrative of the title character, a small, plain-faced, intelligent and honest English orphan. The novel goes through five distinct stages: Jane|Chr(39)| childhood at Gateshead...', 'https://d3i5mgdwi2ze58.cloudfront.net/ydzg0xlc5e6680bthuefj17kqbin');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'The Storyteller', 'A visitor from Peru, happening upon an exhibition of photographs from the Amazon jungle in an obscure Florentine picture gallery, finds his attention drawn to a picture of a tribal storyteller seat...', 'https://d3i5mgdwi2ze58.cloudfront.net/1kc94k49nkkj4kny7v8reym81bny');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Fragments', 'The wisdom poetry of the ancient Greek poet Heraclitus is collected into a single bilingual volume that covers everything from the nature of matter to human psychology. Reprint.', 'https://d3i5mgdwi2ze58.cloudfront.net/7mwcwbiajz7fk95y9t7e8au885qx');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Wuthering Heights', 'The narrative is non-linear, involving several flashbacks, and two primary narrators: Mr. Lockwood and Ellen "Nelly" Dean. The novel opens in 1801, with Mr. Lockwood arriving at Thrushcross Grange,...', 'https://d3i5mgdwi2ze58.cloudfront.net/43ma2b4rlzqbh8181hj7dnpuz5at');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Epic of Gilgamesh', 'The Epic of Gilgamesh is an epic poem from Ancient Iraq and is among the earliest known works of literary writings. Scholars believe that it originated as a series of Sumerian legends and poems abo...', 'https://d3i5mgdwi2ze58.cloudfront.net/ymkq6u5srdt4aby9b41flk9x4fws');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'The Idiot', 'The Idiot is a novel written by the Russian author Fyodor Dostoyevsky and first published in 1868. It was first published serially in Russian in Russky Vestnik, St. Petersburg, 1868-1869. The Idiot...', 'https://d3i5mgdwi2ze58.cloudfront.net/12hwz35xrg2rvp1irky9hu49h805');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Tess of the d Urbervilles', 'Violated by one man, forsaken by another, Tess Durbeyfield is the magnificent and spirited heroine of Thomas Hardy’s immortal work. Of all the great English novelists, no one writes more eloquently...', 'https://d3i5mgdwi2ze58.cloudfront.net/a2j796218g3xpyr8g7joi0z6k7q0');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'The Tale of Genji', 'The Tale of Genji is a classic work of Japanese literature attributed to the Japanese noblewoman Murasaki Shikibu in the early eleventh century, around the peak of the Heian Period. It is sometimes...', 'https://d3i5mgdwi2ze58.cloudfront.net/x7kn9ic9ekuqkjkpinizsmhj252d');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Essays', 'Essays is the title given to a collection of 107 essays written by Michel de Montaigne that was first published in 1580. Montaigne essentially invented the literary form of essay, a short subjectiv...', 'https://d3i5mgdwi2ze58.cloudfront.net/g8tpujchcon3rxy96v0kfjthot1w');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Walden', 'Walden (first published as Walden; or, Life in the Woods) is an American book written by noted transcendentalist Henry David Thoreau, a reflection upon simple living in natural surroundings.', 'https://d3i5mgdwi2ze58.cloudfront.net/695ku0ostz6oansf3n1hrd6fjfsy');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Native Son ', 'The novel tells the story of 20-year old Bigger Thomas, an African American living in utter poverty. Bigger lived in Chicago|Chr(39)| South Side ghetto in the 1930s. Bigger was always getting into troubl...', 'https://d3i5mgdwi2ze58.cloudfront.net/z7csug60545f7486tnl4afhja9nv');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'The Essential Writings of Ralph Waldo Emerson', 'Ralph Waldo Emerson (May 25, 1803 – April 27, 1882) was an American essayist, lecturer, and poet, who led the Transcendentalist movement of the mid-19th century. He was seen as a champion of indivi...', 'https://d3i5mgdwi2ze58.cloudfront.net/w07qru2vrovbv1bp94qwjr8yprwd');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Doctor Faustus', 'Doctor Faustus is a German novel written by Thomas Mann, begun in 1943 and published in 1947 as Doktor Faustus: Das Leben des deutschen Tonsetzers Adrian Leverkühn, erzählt von einem Freunde ("Doct...', 'https://d3i5mgdwi2ze58.cloudfront.net/9n0qvtd6izet5fbv19kgsw61paon');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'To Kill a Mockingbird ', 'As a Southern Gothic novel and a Bildungsroman, the primary themes of To Kill a Mockingbird involve racial injustice and the destruction of innocence. Scholars have noted that Lee also addresses is...', 'https://d3i5mgdwi2ze58.cloudfront.net/f286k461hpyojs41nwzenyd2sv0p');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Gargantua and Pantagruel', 'The Life of Gargantua and of Pantagruel (in French, La vie de Gargantua et de Pantagruel) is a connected series of five novels written in the 16th century by François Rabelais. It is the story of t...', 'https://d3i5mgdwi2ze58.cloudfront.net/kmec73x468xlkaxuiwhkrlqmhkys');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Paradise Lost', 'Paradise Lost is an epic poem in blank verse by the 17th-century English poet John Milton. It was originally published in 1667 in ten books. A second edition followed in 1674, redivided into twelve...', 'https://d3i5mgdwi2ze58.cloudfront.net/0snjhc46o5lxjqk21pli61iarzbk');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Tom Jones', 'A foundling of mysterious parentage brought up by Mr. Allworthy on his country estate, Tom Jones is deeply in love with the seemingly unattainable Sophia Western, the beautiful daughter of the neig...', 'https://d3i5mgdwi2ze58.cloudfront.net/br81vxe29yg2behsk5hrhlopcve0');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'The Catcher in the Rye', 'The Catcher in the Rye is a 1945 novel by J. D. Salinger. Originally published for adults, the novel has become a common part of high school and college curricula throughout the English-speaking wo...', 'https://d3i5mgdwi2ze58.cloudfront.net/arrd4a0qpe7i6ff6jtfmtllqcl6v');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'The Art of Memory', 'The Art of Memory is a 1966 non-fiction book by British historian Frances A. Yates. The book follows the history of mnemonic systems from the classical period of Simonides of Ceos in Ancient Greece...', 'https://d3i5mgdwi2ze58.cloudfront.net/euewr5ef7tuk2t22zbdoe86hbr65');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Middlemarch', 'Middlemarch: A Study of Provincial Life is a novel by George Eliot, the pen name of Mary Anne Evans, later Marian Evans. It is her seventh novel, begun in 1869 and then put aside during the final i...', 'https://d3i5mgdwi2ze58.cloudfront.net/neh1dgi76oop1yebiunqsy38zdk9');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'At Play in the Fields of the Lord', '|Chr(39)|et in the South American jungle, this thriller follows the clash between two misplaced gringos--one who has come to convert the Indians to Christianity, and one who has been hired to kill them.', 'https://d3i5mgdwi2ze58.cloudfront.net/5wbq9lqbzw4bi167xuj791wz4v29');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'All the Pretty Horses', 'All the Pretty Horses is a novel by U.S. author Cormac McCarthy published in 1992. Its romanticism (in contrast to the bleakness of McCarthy|Chr(39)| earlier work) brought the writer much public attention...', 'https://d3i5mgdwi2ze58.cloudfront.net/bmodvsg2b8zfcl1xe5wjo4rxd2r3');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Candide', 'Candide, ou l|Chr(39)|Optimisme is a French satire written in 1759 by Voltaire, a philosopher of the Age of Enlightenment. Candide is characterized by its sarcastic tone and its erratic, fantastical, an...', 'https://d3i5mgdwi2ze58.cloudfront.net/5o5jzoeyp5hnejmc0b8ghburw5fl');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'On the Genealogy of Morality', 'On the Genealogy of Morality, or On the Genealogy of Morals (German: Zur Genealogie der Moral), subtitled "A Polemic" (Eine Streitschrift), is a book by German philosopher Friedrich Nietzsche, comp...', 'https://d3i5mgdwi2ze58.cloudfront.net/2m4em5c3vjbxnpsmo2d0bgrhmn7z');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'A Passage to India ', 'A Passage to India is set against the backdrop of the British Raj and the Indian independence movement in the 1920s. The story revolves around four characters: Dr. Aziz, his British friend Cyril Fi...', 'https://d3i5mgdwi2ze58.cloudfront.net/hiz14hu3aqibatvoxmomnm30qgd8');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'The Sea, The Sea', 'The Sea, the Sea is the 19th novel by Iris Murdoch. It won the Booker Prize in 1978. The Sea, the Sea is a tale of the strange obsessions that haunt a self-satisfied playwright and director as h...', 'https://d3i5mgdwi2ze58.cloudfront.net/7xf4ck5twtzgcr0xzrjr72hgvdwd');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Tristes Tropiques', 'A milestone in the study of culture from the father of structural anthropology. This watershed work records Claude  search for a human society reduced to its most basic expression....', 'https://d3i5mgdwi2ze58.cloudfront.net/q33sfzp2wz8lrsj3aefec0mo6lns');
INSERT INTO Book ( Title,ShortDescription,Image ) VALUES ( 'Their Eyes Were Watching God', 'The main character, an African American woman in her early forties named Janie Crawford, tells the story of her life and journey via an extended flashback to her best friend, Pheoby, so that Pheoby...', 'https://d3i5mgdwi2ze58.cloudfront.net/ikx9vvx60vxclnc63376j71lxjk1');





INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	1	,	1	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	2	,	2	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	3	,	3	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	4	,	4	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	5	,	5	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	6	,	6	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	7	,	7	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	8	,	8	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	9	,	9	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	10	,	10	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	11	,	11	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	12	,	12	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	13	,	13	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	14	,	14	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	15	,	15	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	16	,	16	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	17	,	17	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	18	,	18	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	19	,	19	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	20	,	20	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	21	,	21	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	22	,	22	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	23	,	23	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	24	,	24	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	25	,	25	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	26	,	26	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	27	,	27	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	28	,	28	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	29	,	29	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	30	,	30	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	31	,	31	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	32	,	32	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	33	,	33	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	34	,	34	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	35	,	35	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	36	,	36	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	37	,	37	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	38	,	38	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	39	,	39	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	40	,	40	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	41	,	41	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	42	,	42	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	43	,	43	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	44	,	44	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	45	,	45	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	46	,	46	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	47	,	47	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	48	,	48	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	49	,	49	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	50	,	50	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	51	,	51	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	52	,	52	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	53	,	53	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	54	,	54	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	55	,	55	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	56	,	56	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	57	,	57	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	58	,	58	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	59	,	59	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	60	,	60	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	61	,	61	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	62	,	62	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	63	,	63	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	64	,	64	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	65	,	65	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	66	,	66	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	67	,	67	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	68	,	68	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	69	,	69	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	70	,	70	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	71	,	71	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	72	,	72	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	73	,	73	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	74	,	74	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	75	,	75	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	76	,	76	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	77	,	77	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	78	,	78	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	79	,	79	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	80	,	80	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	81	,	81	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	82	,	82	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	83	,	83	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	84	,	84	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	85	,	85	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	86	,	86	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	87	,	87	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	88	,	88	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	89	,	89	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	90	,	90	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	91	,	91	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	92	,	92	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	93	,	93	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	94	,	94	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	95	,	95	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	96	,	96	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	97	,	97	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	98	,	98	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	99	,	99	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	100	,	100	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	101	,	101	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	102	,	102	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	103	,	103	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	104	,	104	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	105	,	105	);
INSERT INTO Book_Author ( BookId, AuthorId) VALUES (	106	,	106	);



INSERT INTO Track_Changes ( Title, Description, IdBook, UserName) VALUES (	"First"	,	"Let", 1, "Dany", "2022-07-15 08:44:22.887"	);
INSERT INTO Track_Changes ( Title, Description, IdBook, UserName) VALUES (	"First Stanio"	,	"Mr. William Shakespeares Comedies, Histories, & Tragedies is the 1623 published collection of William Shakespeare|Chr(39)| s plays. Modern scholars commonly refer to it as the First Folio. Printed in folio...", 1, "Fanny", "2022-05-15 08:44:22.887"	);


